### ISSUE TITLE
Invalid Error Status/Messaged are returned from the Consent Management API

### ISSUE THREAD

**Issue by ayshsandu** [wso2/carbon-consent-management#56]
**Description:**
Some of the API error responses contain mismatching information. 

ex:
- Internal server error when sent "string" instead "integer" for {purposeID} to GET /consents/purposes/{purposeID} endpoint
- Bad request, when entry is not found for the provided {purposeID} to GET /consents/purposes/{purposeID} endpoint

Need to check all the other API resources for the correct error responses.

**Comment by omindu** [comment]
Will be tracking through: https://github.com/wso2/product-is/issues/2748
